name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: capsiums/pack-action@v1
      with:
        source: cap/
