name: release

on:
  push:
    tags: [ v* ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: capsiums/pack-action@v1
      id: pack
      with:
        source: cap/
        upload-artifact: 'false'
    - name: Upload package to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.pack.outputs.cap-file }}
        tag: ${{ github.ref_name }}
        overwrite: true
        body: "Capsium package built from ${{ github.ref_name }}"
